/**
 * Category metadata derived from the canonical registry.
 * Keep in sync with apps/api/services/category_registry.py.
 */

export const RED_CATEGORY_KEYS = new Set([
  "zombie_renewal",
  "arbitration_waiver",
  "class_bar_standalone",
  "data_succession",
  "gag_clauses",
  "unilateral_interpretation",
  "liquidated_damages_penalties",
  "perpetual_restraint",
  "waiver_of_statutory_rights",
  "device_exploitation",
  "data_selling",
  "private_message_monitoring",
  "content_copyright_transfer",
  "moral_rights_waiver",
  "shortened_limitation_period",
  "ai_training_license",
  "biometric_harvesting",
  "off_platform_tracking",
  "inactivity_fee_seizure",
  "notice_of_breach_delay"
])

export const CATEGORY_HINTS: Record<string, string[]> = {
  unilateral_changes: ["change terms", "amend terms", "without notice", "continued use"],
  retroactive_changes: ["retroactive", "prior conduct", "already collected"],
  auto_renewal: ["auto-renew", "renews automatically", "subscription fee", "billing cycle"],
  zombie_renewal: ["reminder", "automatically renew", "annual"],
  arbitration_waiver: ["binding arbitration", "class action waiver", "jury trial"],
  class_bar_standalone: ["class action", "representative action", "no class"],
  data_rights: ["perpetual license", "irrevocable license", "third parties", "share data"],
  data_succession: ["successor", "merger", "bankruptcy", "assign"],
  cross_service_tracking: ["cross-service", "across our products", "combine data"],
  fee_modification: ["price", "fee", "notice", "grandfather"],
  cancellation_friction: ["non-refundable", "no refunds", "cancel", "cancellation fee"],
  gag_clauses: ["non-disparagement", "negative review", "review"],
  unilateral_interpretation: ["sole discretion", "interpret", "exclusive right"],
  liquidated_damages_penalties: ["liquidated damages", "per breach", "infraction"],
  one_way_attorneys_fees: ["attorneys fees", "prevailing party"],
  no_injunctive_relief: ["injunctive", "equitable relief"],
  mandatory_delay_tactics: ["mediation", "before filing", "days before"],
  perpetual_restraint: ["non-compete", "survive termination"],
  no_assignment_by_user: ["may not assign", "assignable"],
  overbroad_ip_restrictions: ["reverse engineer", "decompile"],
  device_exploitation: ["cryptomining", "processing power", "bandwidth"],
  shadow_profiling: ["contacts", "data broker", "non-user"],
  waiver_of_statutory_rights: ["ccpa", "gdpr", "waive"],
  english_language_supremacy: ["english version", "translation"],
  survival_of_termination_vague: ["survive termination", "necessary provisions"],
  limitation_of_liability: ["limitation of liability", "consequential damages", "not liable"],
  disclaimer_of_warranties: ["as is", "merchantability", "disclaimer of warranties"],
  broad_indemnity: ["indemnify", "hold harmless", "defend"],
  forum_selection_exclusive: ["exclusive jurisdiction", "exclusive venue", "jurisdiction"],
  discretionary_termination: ["sole discretion", "suspend", "terminate"],
  children_data_collection: ["under 13", "children", "parental consent"],
  marketing_communications_burden: ["marketing", "promotional", "sms", "opt out"],
  data_selling: ["sell personal information", "monetize data", "sale of data"],
  private_message_monitoring: ["private message", "direct message", "monitor communications"],
  device_fingerprinting: ["device fingerprint", "pixel tags", "web beacons"],
  continuous_location_tracking: ["precise location", "geolocation", "background location", "gps"],
  content_copyright_transfer: ["assign copyright", "exclusive license", "ownership"],
  moral_rights_waiver: ["moral rights", "waive attribution", "credit"],
  shortened_limitation_period: ["within one year", "time limit", "barred"],
  data_deletion_friction: ["retain after deletion", "backup copies", "no obligation to delete"],
  third_party_disclaimer: ["not responsible third-party", "at your own risk", "no control over"],
  force_majeure_broad: ["force majeure", "acts of god", "beyond our control"],
  ai_training_license: ["train ai", "machine learning", "llm", "training data"],
  biometric_harvesting: ["biometric", "facial recognition", "voiceprint", "fingerprint"],
  off_platform_tracking: ["browser history", "outside the service", "other applications", "keystroke"],
  inactivity_fee_seizure: ["inactivity fee", "dormant account", "unused credits expire"],
  no_refund_on_ban: ["without refund", "forfeit purchases", "no right to a refund"],
  payment_method_updating: ["account updater", "updated credit card", "update payment information"],
  beta_testing_waiver: ["beta features", "experimental", "at your own risk", "pre-release software"],
  notice_of_breach_delay: ["notify within 60 days", "90 days", "120 days", "commercially reasonable time"],
  consent_to_background_check: ["background check", "credit check", "criminal history"]
}
